### ISSUE TITLE
CorrelationQA

### ISSUE THREAD

**Issue by LiqiangJing** [MasaiahHan/CorrelationQA#1]
Hi,
Congrats on the impressive work! Our paper FAITHSCORE: Evaluating Hallucinations in Large Vision-Language Models is very related to your topic.
I wonder if you would mind adding our work to your reference list in the revised version or repo by any chance?
Appreciate it.
Thanks.

**Comment by MasaiahHan** [comment]
Hi,

Thx for your interest in our work! We will read the paper and cite it in our revision version if it is highly related.

Also we would release the evaluation dataset and pipeline code later on github.

Best,
Tianyang
________________________________
发件人: LiqiangJing ***@***.***>
发送时间: Thursday, March 28, 2024 10:21:32 AM
收件人: MasaiahHan/CorrelationQA ***@***.***>
抄送: Subscribed ***@***.***>
主题: [MasaiahHan/CorrelationQA] CorrelationQA (Issue #1)


Hi,
Congrats on the impressive work! Our paper FAITHSCORE: Evaluating Hallucinations in Large Vision-Language Models is very related to your topic.
I wonder if you would mind adding our work to your reference list in the revised version or repo by any chance?
Appreciate it.
Thanks.

―
