### ISSUE TITLE
any timeline to release the dataset? thanks

### ISSUE THREAD

**Issue by hxhcreate** [MasaiahHan/CorrelationQA#2]

**Comment by MasaiahHan** [comment]
Hi,
Thanx for ur interest in our work! We would release our benchmark in the next version in several weeks.
________________________________
发件人: HXH ***@***.***>
发送时间: Monday, May 6, 2024 6:49:30 PM
收件人: MasaiahHan/CorrelationQA ***@***.***>
抄送: Subscribed ***@***.***>
主题: [MasaiahHan/CorrelationQA] any timeline to release the dataset? thanks (Issue #2)


―

**Comment by MasaiahHan** [comment]
Hi, thanx for ur attention. We have released the datasets at https://huggingface.co/datasets/ScottHan/CorrelationQA!
