### ISSUE TITLE
share your code tks?

### ISSUE THREAD

**Issue by henbucuoshanghai** [MasaiahHan/CorrelationQA#4]
https://github.com/TencentARC/BrushNet/issues/48

i dont konw how   tks

**Comment by MasaiahHan** [comment]
> [TencentARC/BrushNet#48](https://github.com/TencentARC/BrushNet/issues/48)
> 
> i dont konw how tks

here is an official repo for a public paper. you can try to connect me in correspond repo. It will be deleted in 10 mins.

**Comment by henbucuoshanghai** [comment]
where? It will be deleted in 10 mins.
