### ISSUE TITLE
StableDiffusionBrushNetPipeline with controlnet

### ISSUE THREAD

**Issue by henbucuoshanghai** [MasaiahHan/CorrelationQA#5]
I change the code of StableDiffusionBrushNetPipeline to support controlnet,but it doesnt works,the input image of controlnet dosent work, the resout is same as input controlnet image,why?

**Comment by TianyangHan** [comment]
For the last warning, this is the official repo for a paper, so do not open an issue here. Go to the brushnet repo and I have commented  under specific issues. I would not help if one more issue been raised here and block the account.
